language: php

php:
  - 7.0
  - hhvm

matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql  # PDO driver for PostgreSQL currently unsupported by HHVM
  allow_failures:
    - php: 7.0
    - php: hhvm

services:
  - memcached
  - redis-server

install:
  # - travis_retry composer self-update && composer update
  # Install PHPCS to validate code standards
  - composer require squizlabs/php_codesniffer 1.5.6
  # Install Cache_Lite for testing
  - composer require pear/cache_lite 1.7.16

before_script:
  # Set up databases for testing
  - mysql -e 'create database joomla_ut;'
  - mysql joomla_ut < tests/unit/schema/mysql.sql
  - psql -c 'create database joomla_ut;' -U postgres
  - psql -d joomla_ut -a -f tests/unit/schema/postgresql.sql
  
  # Set up Apache
  # - ./build/travis/php-apache.sh
  # Enable additional PHP extensions
  - chmod ugo+x build/travis/travis.sh
  - ./build/travis/travis.sh
  - phpenv rehash
  
script:
  - phpunit --configuration travisci-phpunit.xml
  - sh -c "libraries/vendor/bin/phpcs --report=full --extensions=php -p --standard=build/phpcs/Joomla ."
